const state = { profile: localStorage.getItem('sahara-profile') || '', language: 'EN', stream: null, recognition: null };
const dialog = document.querySelector('#toolDialog');
const setup = document.querySelector('#setupDialog');
const content = document.querySelector('#toolContent');
const toast = document.querySelector('#toast');

function showToast(message) { toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 3200); }
function speak(text) { if (!('speechSynthesis' in window)) return showToast('Speech output is not available in this browser.'); speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); utterance.lang = state.language === 'UR' ? 'ur-PK' : 'en-US'; speechSynthesis.speak(utterance); }
function closeDialog() { stopCamera(); if (state.recognition) state.recognition.stop(); dialog.close(); }
function stopCamera() { if (state.stream) { state.stream.getTracks().forEach(track => track.stop()); state.stream = null; } }
function openTool(name) { content.innerHTML = tools[name](); dialog.showModal(); if (name === 'vision') document.querySelector('#cameraStart').focus(); }
function applyProfile() {
 const copy = {
   vision: { status:'VISION SUPPORT · VOICE-FIRST MODE', title:'Tell me what you need. <em>I’ll speak it back.</em>', description:'SAHARA prioritizes voice guidance and camera descriptions. Use Speak to ask for help without searching through screens.' },
   hearing: { status:'HEARING SUPPORT · CAPTIONS-FIRST MODE', title:'See every word. <em>Stay in the moment.</em>', description:'Conversation Bridge is moved to the front, with large captions, Urdu translation, and clear summaries.' },
   motor: { status:'MOTOR SUPPORT · EASY-TAP MODE', title:'One tap is <em>enough.</em>', description:'Every control is larger, separated, and easier to reach. You can also say what you need instead of navigating.' },
   multiple: { status:'PERSONALIZED FOR YOU', title:'Support that adapts <em>with you.</em>', description:'SAHARA combines larger controls, spoken guidance, and clear captions so you can choose what works best right now.' }
 };
 const selected = copy[state.profile] || copy.multiple;
 document.body.dataset.profile = state.profile || 'multiple';
 document.querySelector('#profileStatus').textContent = selected.status;
 document.querySelector('#welcome-title').innerHTML = selected.title;
 document.querySelector('#profileDescription').textContent = selected.description;
}

const tools = {
 vision: () => `<div class="tool-body"><span class="mode-chip">VISION ASSIST</span><h2>Understand what is in front of you.</h2><p>Point your camera at text, a sign, or an everyday object. SAHARA will describe it in a clear, concise way.</p><div class="camera-box" id="cameraBox"><div class="camera-placeholder"><span>⌁</span><strong>Camera is off</strong><p>Nothing is captured until you choose to start.</p></div></div><button id="cameraStart" class="primary-button">Turn on camera</button><button id="analyzeVision" class="secondary-button" disabled>Ask SAHARA</button><button id="demoVision" class="secondary-button">Try demo result</button><div id="visionResult"></div></div>`,
 conversation: () => `<div class="tool-body"><span class="mode-chip">CONVERSATION BRIDGE</span><h2>Keep up with the conversation.</h2><p>Live captions appear here in large, easy-to-read text. Your microphone stays on only while captions are active.</p><div class="caption-box" id="captions" aria-live="polite">Captions will appear here…</div><div class="caption-status"><span class="pulse-dot"></span><span id="captionStatus">Ready when you are</span></div><button id="captionStart" class="primary-button">Start captions</button><button id="summarize" class="secondary-button">Summarize</button></div>`,
 read: () => `<div class="tool-body"><span class="mode-chip">READ ALOUD</span><h2>Let SAHARA read it to you.</h2><p>Paste or type text below, then choose Read aloud.</p><textarea id="readerText" class="reader-input" aria-label="Text to read aloud" placeholder="Type or paste text here…"></textarea><div style="margin-top:16px"><button id="readButton" class="primary-button">Read aloud</button><button id="clearReader" class="secondary-button">Clear</button></div></div>`,
 help: () => `<div class="tool-body"><span class="mode-chip">ASK SAHARA</span><h2>Tell me what you need.</h2><p>Try “I need help reading a sign”, “start captions”, or “read this aloud.”</p><textarea id="helpText" class="reader-input" aria-label="Describe what you need" placeholder="How can SAHARA help?"></textarea><div style="margin-top:16px"><button id="helpSend" class="primary-button">Get help</button></div><div id="helpAnswer"></div></div>`,
 safety: () => `<div class="tool-body"><span class="mode-chip">SAFETY CHECK-IN</span><h2>Share a check-in with someone you trust.</h2><p>SAHARA will prepare a message with your current location. You review it before it is shared.</p><div class="result-card" id="locationResult"><strong>Your location is private until you choose Share.</strong><span>Tap below to create your check-in.</span></div><div class="safety-actions"><button id="getLocation" class="share-button">Create safety check-in</button><button id="shareLocation" class="copy-button" disabled>Share or copy message</button></div></div>`
};

document.addEventListener('click', async event => {
 const button = event.target.closest('button'); if (!button) return;
 if (button.matches('[data-tool]')) return openTool(button.dataset.tool);
 if (button.classList.contains('close-button')) return closeDialog();
 if (button.id === 'listenButton') return startVoicePrompt();
 if (button.id === 'sceneSpeak') return speak('Clear path to the exit, slightly right. A wet-floor sign is two steps ahead on your left.');
 if (button.id === 'safetyButton') return openTool('safety');
 if (button.id === 'languageButton') { state.language = state.language === 'EN' ? 'UR' : 'EN'; button.innerHTML = `${state.language} <span aria-hidden="true">⌄</span>`; document.documentElement.lang = state.language === 'UR' ? 'ur' : 'en'; showToast(state.language === 'UR' ? 'اردو موڈ فعال ہے' : 'English mode enabled'); }
 if (button.id === 'settingsButton') { localStorage.removeItem('sahara-profile'); setup.showModal(); }
 if (button.matches('[data-profile]')) { state.profile = button.dataset.profile; document.querySelectorAll('[data-profile]').forEach(b => b.setAttribute('aria-pressed','false')); button.setAttribute('aria-pressed','true'); document.querySelector('#continueSetup').disabled = false; }
 if (button.id === 'continueSetup') { localStorage.setItem('sahara-profile', state.profile); applyProfile(); setup.close(); showToast('Your SAHARA experience is ready.'); }
 if (button.id === 'cameraStart') return startCamera();
 if (button.id === 'analyzeVision') return analyzeVision();
 if (button.id === 'demoVision') return visionResult();
 if (button.id === 'captionStart') return startCaptions();
 if (button.id === 'summarize') return summarizeCaptions();
 if (button.id === 'readButton') { const text = document.querySelector('#readerText').value.trim(); text ? speak(text) : showToast('Please add some text first.'); }
 if (button.id === 'clearReader') document.querySelector('#readerText').value = '';
 if (button.id === 'helpSend') return helpAnswer();
 if (button.id === 'getLocation') return getLocation();
 if (button.id === 'shareLocation') return shareLocation();
});

async function startCamera() { const box = document.querySelector('#cameraBox'); try { state.stream = await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false}); box.innerHTML = '<video id="cameraPreview" autoplay playsinline muted aria-label="Live camera preview"></video>'; document.querySelector('#cameraPreview').srcObject = state.stream; document.querySelector('#cameraStart').textContent = 'Camera is on'; document.querySelector('#cameraStart').disabled = true; document.querySelector('#analyzeVision').disabled = false; } catch { showToast('Camera permission was not granted. You can still try the demo result.'); } }
function visionResult() { const result = `A sign with a left arrow. It says: “Reception and information desk.”`; document.querySelector('#visionResult').innerHTML = `<div class="result-card"><strong>SAHARA sees</strong>${result}<br><button class="secondary-button" id="speakVision" style="margin:12px 0 0">Speak result</button></div>`; document.querySelector('#speakVision').onclick = () => speak(result); }
async function analyzeVision() { const video = document.querySelector('#cameraPreview'); if (!video) return showToast('Turn on the camera first.'); const canvas = document.createElement('canvas'); canvas.width = video.videoWidth || 960; canvas.height = video.videoHeight || 540; canvas.getContext('2d').drawImage(video, 0, 0, canvas.width, canvas.height); const button = document.querySelector('#analyzeVision'); button.textContent = 'Understanding…'; button.disabled = true; try { const response = await fetch('/api/vision', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({image:canvas.toDataURL('image/jpeg', .82), language:state.language}) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'SAHARA could not analyze this image.'); const answer = data.answer; document.querySelector('#visionResult').innerHTML = `<div class="result-card"><strong>SAHARA sees</strong>${answer}<br><button class="secondary-button" id="speakVision" style="margin:12px 0 0">Speak result</button></div>`; document.querySelector('#speakVision').onclick = () => speak(answer); } catch (error) { showToast(error.message); } finally { button.textContent = 'Ask SAHARA'; button.disabled = false; } }
function startCaptions() { const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!SpeechRecognition) { document.querySelector('#captions').textContent = 'Live speech recognition is not supported in this browser. Try Chrome for this feature.'; return; } const recognition = new SpeechRecognition(); state.recognition = recognition; recognition.continuous=true; recognition.interimResults=true; recognition.lang=state.language==='UR'?'ur-PK':'en-US'; recognition.onstart=()=>{document.querySelector('#captionStatus').textContent='Listening…'; document.querySelector('#captionStart').textContent='Captions active';}; recognition.onresult=e=>{let text=''; for(let i=e.resultIndex;i<e.results.length;i++) text+=e.results[i][0].transcript; document.querySelector('#captions').textContent=text||'Listening…';}; recognition.onerror=()=>{document.querySelector('#captionStatus').textContent='Could not hear clearly. Try again.';}; recognition.start(); }
function summarizeCaptions() { const text = document.querySelector('#captions').textContent; if (text.includes('appear here') || text === 'Listening…') return showToast('Start captions first, then ask for a summary.'); document.querySelector('#captions').insertAdjacentHTML('afterend', `<div class="result-card"><strong>Quick summary</strong>${text.length > 120 ? text.slice(0,120)+'…' : text}</div>`); }
function helpAnswer() { const input = document.querySelector('#helpText').value.trim().toLowerCase(); const answer = input.includes('caption') ? 'I can open Conversation Bridge for large live captions.' : input.includes('read') || input.includes('sign') ? 'Open Understand my surroundings to read a sign with your camera, or choose Read aloud for pasted text.' : 'I can help you understand your surroundings, follow conversations, read text aloud, or create a safety check-in.'; document.querySelector('#helpAnswer').innerHTML=`<div class="result-card"><strong>SAHARA suggests</strong>${answer}</div>`; speak(answer); }
function getLocation() { const output=document.querySelector('#locationResult'); if (!navigator.geolocation) { output.innerHTML='<strong>Location is not supported in this browser.</strong>'; return; } output.innerHTML='<strong>Finding your location…</strong>'; navigator.geolocation.getCurrentPosition(pos=>{const {latitude,longitude}=pos.coords; const link=`https://maps.google.com/?q=${latitude},${longitude}`; output.innerHTML=`<strong>Your check-in is ready.</strong><br><span id="shareMessage">Hi, this is a safety check-in from SAHARA. My current location: ${link}</span>`; document.querySelector('#shareLocation').disabled=false;},()=>{output.innerHTML='<strong>We could not access your location.</strong><br>Check browser permissions and try again.';}); }
async function shareLocation() { const text=document.querySelector('#shareMessage').textContent; try { if(navigator.share) await navigator.share({title:'SAHARA safety check-in',text}); else { await navigator.clipboard.writeText(text); showToast('Safety check-in copied to your clipboard.'); } } catch { showToast('Your safety check-in is ready to copy.'); } }
function startVoicePrompt() { const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!SpeechRecognition) return showToast('Voice input works best in Chrome. Choose a tool to continue.'); const rec=new SpeechRecognition(); rec.lang=state.language==='UR'?'ur-PK':'en-US'; document.querySelector('#voicePromptText').textContent='Listening…'; rec.onresult=e=>{const said=e.results[0][0].transcript.toLowerCase(); document.querySelector('#voicePromptText').textContent=`“${said}”`; if(said.includes('read')||said.includes('text'))openTool('read'); else if(said.includes('caption')||said.includes('conversation'))openTool('conversation'); else if(said.includes('camera')||said.includes('see'))openTool('vision'); else openTool('help');}; rec.onerror=()=>{document.querySelector('#voicePromptText').textContent='Tap to speak to SAHARA';}; rec.start(); }
if (!state.profile) setup.showModal(); else applyProfile();
